### ISSUE TITLE
How about moving to mantrajs org

### ISSUE THREAD

**Issue by arunoda** [MaksTr/meteor-mantra-kickstarter#1]
Hi, 

This is great guys.
How about moving this repo to mantrajs org.

@Makstr what do you think?

**Comment by makstr** [comment]
That sounds like a great idea :-)  Please instruct me how to do this properly

**Comment by makstr** [comment]
Should I just transfert it to "mantrajs"?

**Comment by arunoda** [comment]
Hey, I just added you to mantrajs organization. You can work on there.

**Comment by arunoda** [comment]
You can transfer now. I think.
