### ISSUE TITLE
 Cannot find module 'react-simple-di' & "There is no route for the path: /"

### ISSUE THREAD

**Issue by zackleman** [MaksTr/meteor-mantra-kickstarter#14]
I cloned the correct version of the repo, ran npm install, and then started meteor. The app starts up fine, but the browser is blank with these two errors in the console.

```
Cannot find module 'react-simple-di' 

There is no route for the path: /
```

I assume this might be some sort of module issue.  I am still in the process of learning how to use modules. The mantra sample blog app works fine for me. Any ideas on what might be going wrong? Thanks!

<img width="1115" alt="screen shot 2016-02-23 at 2 51 35 pm" src="https://cloud.githubusercontent.com/assets/6403966/13269524/01902234-da3d-11e5-8244-7134734c2567.png">

**Comment by stivaugoin** [comment]
Same problem here!

**Comment by mozky** [comment]
Seems like "react-simple-di" and "react-komposer" are missing, you can install them with `npm install react-simple-di react-komposer` or add them to the package.json file and installing again. Created PR #15 with the modified  #package.json file.
