### ISSUE TITLE
Kickstarter: go lean - move _colors to example repo?

### ISSUE THREAD

**Issue by sandervanhooft** [MaksTr/meteor-mantra-kickstarter#17]
I've been working on a personal project with this kickstarter package. I think the _colors module is a great example module, but this kickstarter is not intended as a sample project. It is intended to kickstart new mantra projects. I now need to manually remove it before actually starting to write some code.

_Can we move the _colors module to a kickstarter example repo or simply drop it?_

**Comment by makstr** [comment]
You can disable the _colors module in the /client/main.js altogether very quickly by commenting out 2 lines. For others the _colors module may act as an example of implementation
