### ISSUE TITLE
Module names with underscore _

### ISSUE THREAD

**Issue by purplecones** [MaksTr/meteor-mantra-kickstarter#18]
I was curious as to why some modules are prefixed with an underscore and the convention around it?

![screen shot 2016-02-29 at 1 48 34 pm](https://cloud.githubusercontent.com/assets/136654/13405074/cb33b6d0-deea-11e5-9988-d278b582bd01.png)

**Comment by rgstephens** [comment]
I agree, why is there a change in the naming convention?
