### ISSUE TITLE
Meteor 1.3 beta 11 , TypeError: Collections is undefined

### ISSUE THREAD

**Issue by gantu** [MaksTr/meteor-mantra-kickstarter#21]
I am getting TypeError: Collections is undefined on meteor 13 beta 11. 
Collections inside composers can not been identified.

```
export const collectionComposer = ({context}, onData) => {
  const {Meteor, Collections} = context();
  if (Meteor.subscribe('_colors.list').ready()) {
    const collection = Collections._colors.find().fetch();
    onData(null, {collection});
  }
};
```

What can be the issue?

**Comment by fallenpeace** [comment]
is Collections in your context?

**Comment by gantu** [comment]
I have fixed the issue, it was more mantra spec related than meteor. 
By properly exporting the problem is fixed.

**Comment by natecox** [comment]
@gantu can you document your fix for this (code sample) in case other come across it too?
