### ISSUE TITLE
Best way to add LESS support?

### ISSUE THREAD

**Issue by sandervanhooft** [MaksTr/meteor-mantra-kickstarter#22]
What's would be the preferred way for implementing LESS support? Should I use the meteor package, or a NPM package with some config?

If NPM is preferred, how should I configure this?

**Comment by makstr** [comment]
Whichever suits you better npm or meteor package. My experience is that running less may actually increase build times, so it's worth considering compiling manually from a command line

**Comment by sandervanhooft** [comment]
Thank you! So if I would use a manual less compiler, I would also manually copy the generated CSS into  the project? Or is there a way to auto-include this?
