### ISSUE TITLE
Last week experiences

### ISSUE THREAD

**Issue by sandervanhooft** [MaksTr/meteor-mantra-kickstarter#28]
Hi,

These are my primary findings while working with the Mantra Kickstarter package during last week:
1. I really love it. Will be using it for all my new projects. Let me know if I can contribute, would love to join the team.
2. I had troubles integrating an existing template into the current template module, which I eventually removed manually. I have installed the less and huttonr:bootstrap3 Meteor packages, and the NPM react-bootstrap package. This really kickstarts front-end (Bootstrap powered) development. Unfortunately I'm not able to share the template code (copyright...), but let me know if I can help you integrate the mentioned packages into the Kickstarter app.

Enjoy your weekend,

Sander

**Comment by makstr** [comment]
@sandervanhooft great to hear :) This project when published was a work in progress. I will be updating it extensively this week. My first priority is clearing out all the bugs, and doing some code cleanup. After that we can create a more detailed roadmap. One thing I'd like to explore a bit more is webpack integration

**Comment by sandervanhooft** [comment]
@Makstr Perhaps you should take a look at https://github.com/mantrajs/kickstart-mantrajs-webpack then. I am juggling a bit between your kickstarter and that one. :)
