### ISSUE TITLE
Redirecting inside Composers? 

### ISSUE THREAD

**Issue by gantu** [MaksTr/meteor-mantra-kickstarter#31]
Hi, 
According to mantra specs : If you need to redirect upon some condition (for example user is not authorized) use an action instead of route options like FlowRouter’s triggersEnter. Call the action from component or container’s composer function.

In colors module redirection is commented out as below: 

 meteor-mantra-kickstarter/client/modules/_colors/composers/colors/single.jsx

```
 if (Meteor.subscribe('_colors.single', _id).ready()) {
    const record = Collections._colors.findOne(_id);
    if (record) {
      onData(null, {record, error});
    } else {
      // FlowRouter.go('/colors');
    }
  }
```

Please help to figure out what is the proper way to redirect inside composers.

Thank you.

**Comment by zaklampert** [comment]
This is also happening in the users module here https://github.com/mantrajs/meteor-mantra-kickstarter/blob/v0.2.1/client/modules/_users/routes.jsx

I'd also like to know if this is the correct way of handling this @arunoda

**Comment by TeemoWan** [comment]
I think that it should be display 404 page,not redirect.

**Comment by makstr** [comment]
This is and old branch, I am currently refactoring the entire app. A new version should be ready by the end of this weekend
