### ISSUE TITLE
{tcomb-form} vs {formsy-react}

### ISSUE THREAD

**Issue by sandervanhooft** [MaksTr/meteor-mantra-kickstarter#34]
Just curious: why both in this kickstarter? When to choose one over the other?

**Comment by makstr** [comment]
I brought in tcomb on board because formsy-react has been unmaintained for some time now, tcomb-form also seems to be following better patterns

**Comment by sandervanhooft** [comment]
Ok, that's great! Do you know by any chance if there's a way to use Astronomy for tcomb's schema input?
