### ISSUE TITLE
Consider the integration of a React component playground

### ISSUE THREAD

**Issue by mquandalle** [MaksTr/meteor-mantra-kickstarter#9]
I just find out [Atellier](https://github.com/scup/atellier) which looks pretty cool, and as it became more and more accepted as a good practice to develop, test, and document individuals components outside the context of the main application but instead in a playground environment, I think something like Atellier would be good to have in a Mantra starter kit.

It sure is not easy to run different servers in a clean way with the current Meteor build-tool but since you already have done that for Graph_i_ql (I haven’t looked at the implementation), I’m putting Atellier on the table.

**Comment by natecox** [comment]
Interesting concept, I'd be curious to see how it plays out within the context of Meteor.

**Comment by arunoda** [comment]
I think we should post this against the core mantrajs repo.  We could may be load all the components from the disk without starting Meteor.

This will be awesome.

**Comment by mquandalle** [comment]
Also for those unfamiliar with the idea of developing UI components outside of the main application, I would recommend watching https://www.youtube.com/watch?v=nQo0EdHNjto (in JavaScript) and/or https://www.youtube.com/watch?v=G7Z_g2fnEDg (in ClojureScript).

**Comment by mquandalle** [comment]
@arunoda Do you want me to close this issue and re-open it on https://github.com/mantrajs/mantra-core/issues?

**Comment by arunoda** [comment]
@mquandalle That's better. I guess we get more eyes into this if then.

**Comment by mquandalle** [comment]
It seems like Storybook is the fix!
